version: 2.1

executors:

  python:

    parameters:
      tag:
        description: circleci/python docker tag
        type: string

    docker:
      - image: circleci/python:<< parameters.tag >>

commands:

  dependencies:

    steps:
      - run:
          name: Install Dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            python -m pip install --upgrade pip setuptools
            pip install poetry
            poetry config settings.virtualenvs.in-project true
            poetry install

jobs:

  test:

    parameters:
      tag:
        description: circleci/python docker tag
        type: string

    executor:
      name: python
      tag: << parameters.tag >>

    steps:
      - checkout

      - dependencies

      - run:
          name: Pytest
          command: |
            source .venv/bin/activate
            poetry run coverage run -m pytest --junit-xml=test-results/pytest/results.xml

      - run:
          name: Codecov
          command: |
            source .venv/bin/activate
            poetry run codecov

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results

  lint:

    executor:
      name: python
      tag: 3.7.1

    steps:
      - checkout

      - dependencies

      - run:
          name: Mypy
          command: |
            source .venv/bin/activate
            poetry run mypy --ignore-missing-imports --strict --allow-untyped-decorators euler
            poetry run mypy --ignore-missing-imports --strict --allow-untyped-decorators tests

      - run:
          name: Pylint
          # C0103: invalid-name
          # C0301: line-too-long
          command: |
            source .venv/bin/activate
            poetry run pylint -d C0103 euler
            poetry run pylint -d C0103,C0301 tests

workflows:

  version: 2

  commit:

    jobs:
      - test:
          name: python 3.7
          tag: 3.7.1
      - lint

  weekly:

    jobs:
      - test:
          name: python 3.7
          tag: 3.7.1
      - lint

    triggers:
      - schedule:
          cron: "1 0 * * 1"
          filters:
            branches:
              only:
                - master
